# Generated by Django 4.2.7 on 2023-11-05 16:40

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Bookshelf",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("author", models.CharField(max_length=200)),
                ("isbn", models.CharField(max_length=200)),
                ("summary", models.TextField(max_length=200)),
                ("genre", models.CharField(max_length=200)),
                ("publish_date", models.DateField()),
            ],
        ),
    ]
